const lessonTitle = "丑石";

const lessonData = [
    // ===== 第1段 =====
    ["我", "wǒ", "I", "Saya"],
    ["常常", "cháng cháng", "often", "selalu"],
    ["遗憾", "yí hàn", "regret", "kesal"],
    ["我家", "wǒ jiā", "my house", "rumah saya"],
    ["门前", "mén qián", "in front of", "di hadapan"],
    ["的", "de", "", ""],
    ["那块", "nà kuài", "that piece of", "ketul itu"],
    ["丑石", "chǒu shí", "ugly stone", "batu buruk"],
    ["呢", "ne", "", ""],
    ["：", "", "", ""],
    ["它", "tā", "It", "Ia"],
    ["黑黝黝地", "hēi yǒu yǒu de", "darkly", "hitam pekat"],
    ["卧在", "wò zài", "lying on", "terbaring di"],
    ["那里", "nà lǐ", "there", "sana"],
    ["，", "", "", ""],
    ["牛似的", "niú shì de", "ox-like", "seperti lembu"],
    ["模样", "mú yàng", "appearance", "rupa"],
    ["；", "", "", ""],
    ["谁", "shuí", "No one", "Sesiapa pun"],
    ["也", "yě", "also", "juga"],
    ["不知道", "bù zhī dào", "doesn't know", "tidak tahu"],
    ["是", "shì", "", ""],
    ["什么", "shén me", "what", "apa"],
    ["时候", "shí hou", "time", "masa"],
    ["留在", "liú zài", "left at", "tertinggal di"],
    ["这里的", "zhè lǐ de", "here", "sini"],
    ["，", "", "", ""],
    ["谁", "shuí", "no one", "tiada siapa"],
    ["也", "yě", "also", "juga"],
    ["不去", "bù qù", "doesn't", "tidak"],
    ["理会", "lǐ huì", "pay attention", "mengendahkan"],
    ["它", "tā", "it", "ia"],
    ["。", "", "", ""],
    ["只是", "zhǐ shì", "Only", "Cuma"],
    ["麦收", "mài shōu", "wheat harvest", "menuai gandum"],
    ["时节", "shí jié", "season", "musim"],
    ["，", "", "", ""],
    ["门前", "mén qián", "in front", "di hadapan"],
    ["摊了", "tān le", "spread", "menghamparkan"],
    ["麦子", "mài zi", "wheat", "gandum"],
    ["，", "", "", ""],
    ["奶奶", "nǎi nai", "Grandma", "Nenek"],
    ["总是", "zǒng shì", "always", "selalu"],
    ["要", "yào", "would", "akan"],
    ["说", "shuō", "say", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这块", "zhè kuài", "This", "Ketul ini"],
    ["丑石", "chǒu shí", "ugly stone", "batu buruk"],
    ["，", "", "", ""],
    ["多碍", "duō ài", "so obstructive", "sangat menghalang"],
    ["地面", "dì miàn", "ground", "tanah"],
    ["哟", "yo", "", ""],
    ["，", "", "", ""],
    ["多时", "duō shí", "when", "bila"],
    ["把它", "bǎ tā", "it", "ia"],
    ["搬走", "bān zǒu", "move away", "alihkan"],
    ["吧", "ba", "", ""],
    ["。”", "", "", ""],
    ["于是", "yú shì", "Then", "Maka"],
    ["，", "", "", ""],
    ["伯父家", "bó fù jiā", "Uncle's family", "Keluarga bapa saudara"],
    ["盖房", "gài fáng", "building a house", "membina rumah"],
    ["，", "", "", ""],
    ["想", "xiǎng", "wanted", "mahu"],
    ["以它", "yǐ tā", "to use it", "menggunakannya"],
    ["垒", "lěi", "build", "membina"],
    ["山墙", "shān qiáng", "wall", "dinding"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["苦于", "kǔ yú", "suffered from", "terpaksa"],
    ["它", "tā", "it", "ia"],
    ["极不", "jí bù", "very irregular", "sangat tidak"],
    ["规则", "guī zé", "regular", "teratur"],
    ["，", "", "", ""],
    ["没", "méi", "no", "tiada"],
    ["棱角儿", "léng jiǎo r", "edges", "bucu"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["没", "méi", "no", "tiada"],
    ["平面儿", "píng miàn r", "flat surface", "permukaan rata"],
    ["；", "", "", ""],
    ["用", "yòng", "using", "menggunakan"],
    ["錾", "zàn", "chisel", "pahat"],
    ["破开", "pò kāi", "break open", "memecahkan"],
    ["吧", "ba", "", ""],
    ["，", "", "", ""],
    ["又", "yòu", "again", "lagi"],
    ["懒得", "lǎn de", "too lazy", "malas"],
    ["花", "huā", "spend", "membazir"],
    ["那么", "nà me", "so much", "begitu"],
    ["大气力", "dà qì lì", "effort", "tenaga"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["河滩", "hé tān", "riverbank", "tebing sungai"],
    ["并不", "bìng bù", "not", "tidak"],
    ["甚远", "shèn yuǎn", "far", "jauh"],
    ["，", "", "", ""],
    ["随便", "suí biàn", "casually", "sewenang-wenang"],
    ["去", "qù", "go", "pergi"],
    ["掮一块", "qián yí kuài", "carry a piece", "bawa seketul"],
    ["回来", "huí lái", "back", "pulang"],
    ["，", "", "", ""],
    ["哪一块", "nǎ yí kuài", "any one", "mana-mana"],
    ["也", "yě", "also", "juga"],
    ["比它强", "bǐ tā qiáng", "better than it", "lebih baik daripadanya"],
    ["。", "", "", ""],
    ["房", "fáng", "House", "Rumah"],
    ["盖起来", "gài qǐ lái", "built", "siap dibina"],
    ["，", "", "", ""],
    ["压铺", "yā pù", "lay", "membina"],
    ["台阶", "tái jiē", "steps", "tangga"],
    ["，", "", "", ""],
    ["伯父", "bó fù", "uncle", "bapa saudara"],
    ["也", "yě", "also", "juga"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["看上", "kàn shàng", "favour", "memilih"],
    ["它", "tā", "it", "ia"],
    ["。", "", "", ""],
    ["有一年", "yǒu yì nián", "One year", "Pada suatu tahun"],
    ["，", "", "", ""],
    ["来了", "lái le", "came", "datang"],
    ["一个", "yí gè", "a", "seorang"],
    ["石匠", "shí jiàng", "stonemason", "tukang batu"],
    ["，", "", "", ""],
    ["为", "wèi", "for", "untuk"],
    ["我家", "wǒ jiā", "my family", "keluarga saya"],
    ["洗", "xǐ", "dress", "mengasah"],
    ["一台", "yì tái", "a", "sebuah"],
    ["石磨", "shí mò", "millstone", "batu kilang"],
    ["，", "", "", ""],
    ["奶奶", "nǎi nai", "Grandma", "Nenek"],
    ["又", "yòu", "again", "lagi"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["用", "yòng", "Use", "Guna"],
    ["这块", "zhè kuài", "this", "ketul ini"],
    ["丑石", "chǒu shí", "ugly stone", "batu buruk"],
    ["吧", "ba", "", ""],
    ["，", "", "", ""],
    ["省得", "shěng de", "save the trouble", "menjimatkan"],
    ["从", "cóng", "from", "dari"],
    ["远处", "yuǎn chù", "far away", "jauh"],
    ["搬动", "bān dòng", "moving", "mengalih"],
    ["。”", "", "", ""],
    ["石匠", "shí jiàng", "Stonemason", "Tukang batu"],
    ["看了", "kàn le", "looked", "melihat"],
    ["看", "kàn", "", ""],
    ["，", "", "", ""],
    ["摇着", "yáo zhe", "shook", "menggeleng"],
    ["头", "tóu", "head", "kepala"],
    ["，", "", "", ""],
    ["嫌", "xián", "disliked", "menghina"],
    ["它", "tā", "it", "ia"],
    ["石质", "shí zhì", "texture", "tekstur"],
    ["太细", "tài xì", "too fine", "terlalu halus"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["不", "bù", "not", "tidak"],
    ["采用", "cǎi yòng", "use", "menggunakan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["它", "tā", "It", "Ia"],
    ["不像", "bù xiàng", "unlike", "tidak seperti"],
    ["汉白玉", "hàn bái yù", "white marble", "marmar putih"],
    ["那样", "nà yàng", "so", "begitu"],
    ["的", "de", "", ""],
    ["细腻", "xì nì", "fine texture", "tekstur halus"],
    ["，", "", "", ""],
    ["可以", "kě yǐ", "can", "boleh"],
    ["凿下", "záo xià", "carve", "mengukir"],
    ["刻字", "kè zì", "carve words", "mengukir tulisan"],
    ["雕花", "diāo huā", "carve flowers", "mengukir bunga"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["不像", "bù xiàng", "unlike", "tidak seperti"],
    ["大青石", "dà qīng shí", "blue stone", "batu biru"],
    ["那样", "nà yàng", "so", "begitu"],
    ["的", "de", "", ""],
    ["光滑", "guāng huá", "smooth", "licin"],
    ["，", "", "", ""],
    ["可以", "kě yǐ", "can", "boleh"],
    ["供来", "gòng lái", "used for", "digunakan untuk"],
    ["浣纱", "huàn shā", "wash", "membasuh"],
    ["捶衣", "chuí yī", "beat clothes", "memukul pakaian"],
    ["；", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["静静地", "jìng jìng de", "quietly", "dengan senyap"],
    ["卧在", "wò zài", "lying", "terbaring di"],
    ["那里", "nà lǐ", "there", "sana"],
    ["，", "", "", ""],
    ["院边", "yuàn biān", "beside the yard", "tepi halaman"],
    ["的", "de", "", ""],
    ["槐荫", "huái yīn", "locust shade", "naungan pokok locust"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["庇覆", "bì fù", "cover", "melindungi"],
    ["它", "tā", "it", "ia"],
    ["，", "", "", ""],
    ["花儿", "huā r", "flowers", "bunga-bungaan"],
    ["也", "yě", "also", "juga"],
    ["不再", "bù zài", "no longer", "tidak lagi"],
    ["在", "zài", "at", "di"],
    ["它身边", "tā shēn biān", "beside it", "sisinya"],
    ["生长", "shēng zhǎng", "grow", "tumbuh"],
    ["。", "", "", ""],
    ["荒草", "huāng cǎo", "Weeds", "Rumput liar"],
    ["便", "biàn", "then", "lalu"],
    ["繁衍", "fán yǎn", "multiply", "tumbuh"],
    ["出来", "chū lái", "", ""],
    ["，", "", "", ""],
    ["枝蔓", "zhī wàn", "vines", "rumpun"],
    ["上下", "shàng xià", "up and down", "naik turun"],
    ["，", "", "", ""],
    ["慢慢地", "màn màn de", "slowly", "perlahan-lahan"],
    ["，", "", "", ""],
    ["竟", "jìng", "even", "malah"],
    ["锈上", "xiù shàng", "got", "terkena"],
    ["了", "le", "", ""],
    ["绿苔", "lǜ tái", "green moss", "lumut hijau"],
    ["、", "", "", ""],
    ["黑斑", "hēi bān", "black spots", "bintik hitam"],
    ["。", "", "", ""],
    ["我们", "wǒ men", "We", "Kami"],
    ["这些", "zhè xiē", "these", "ini"],
    ["做孩子的", "zuò hái zi de", "children", "kanak-kanak"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["讨厌", "tǎo yàn", "hate", "benci"],
    ["起", "qǐ", "", ""],
    ["它来", "tā lái", "it", "ia"],
    ["，", "", "", ""],
    ["曾", "céng", "once", "pernah"],
    ["合伙", "hé huǒ", "together", "bersama"],
    ["要", "yào", "wanted", "mahu"],
    ["搬走", "bān zǒu", "move away", "alihkan"],
    ["它", "tā", "it", "ia"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["力气", "lì qì", "strength", "tenaga"],
    ["又", "yòu", "also", "juga"],
    ["不足", "bù zú", "not enough", "tidak cukup"],
    ["；", "", "", ""],
    ["虽", "suī", "although", "walaupun"],
    ["时时", "shí shí", "often", "kerap"],
    ["咒骂", "zhòu mà", "curse", "memaki"],
    ["它", "tā", "it", "ia"],
    ["，", "", "", ""],
    ["嫌弃", "xián qì", "despise", "menghina"],
    ["它", "tā", "it", "ia"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["无可奈何", "wú kě nài hé", "could do nothing", "tidak dapat berbuat apa-apa"],
    ["，", "", "", ""],
    ["只好", "zhǐ hǎo", "had to", "terpaksa"],
    ["任它", "rèn tā", "let it", "membiarkannya"],
    ["留在", "liú zài", "stay at", "tinggal di"],
    ["那里", "nà lǐ", "there", "sana"],
    ["去了", "qù le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["稍稍", "shāo shāo", "Slightly", "Agak"],
    ["能", "néng", "can", "boleh"],
    ["安慰", "ān wèi", "comfort", "menghiburkan"],
    ["我们的", "wǒ men de", "us", "kami"],
    ["，", "", "", ""],
    ["是", "shì", "was", "ialah"],
    ["在", "zài", "on", "di"],
    ["那石上", "nà shí shàng", "that stone", "batu itu"],
    ["有", "yǒu", "there was", "ada"],
    ["一个", "yí gè", "a", "sebuah"],
    ["不大不小", "bù dà bù xiǎo", "not big not small", "tidak besar tidak kecil"],
    ["的", "de", "", ""],
    ["坑凹儿", "kēng āo r", "hollow", "lekuk"],
    ["，", "", "", ""],
    ["雨天", "yǔ tiān", "rainy days", "hari hujan"],
    ["就", "jiù", "then", "lalu"],
    ["盛满", "shèng mǎn", "filled", "penuh"],
    ["了", "le", "", ""],
    ["水", "shuǐ", "water", "air"],
    ["。", "", "", ""],
    ["常常", "cháng cháng", "Often", "Selalu"],
    ["雨过", "yǔ guò", "rain passed", "hujan berlalu"],
    ["三天", "sān tiān", "three days", "tiga hari"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["地上", "dì shàng", "the ground", "tanah"],
    ["已经", "yǐ jīng", "already", "telah"],
    ["干燥", "gān zào", "dry", "kering"],
    ["，", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["石凹里", "shí āo lǐ", "in the hollow", "dalam lekuk"],
    ["水儿", "shuǐ r", "water", "air"],
    ["还有", "hái yǒu", "still had", "masih ada"],
    ["，", "", "", ""],
    ["鸡儿", "jī r", "chickens", "ayam-ayam"],
    ["便", "biàn", "then", "lalu"],
    ["去", "qù", "go", "pergi"],
    ["那里", "nà lǐ", "there", "sana"],
    ["渴饮", "kě yǐn", "drink", "minum"],
    ["。", "", "", ""],
    ["每每", "měi měi", "Whenever", "Setiap kali"],
    ["到了", "dào le", "arrived", "tiba"],
    ["十五", "shí wǔ", "the fifteenth", "ke-15"],
    ["的", "de", "", ""],
    ["夜晚", "yè wǎn", "night", "malam"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["盼着", "pàn zhe", "looked forward", "menanti"],
    ["满月", "mǎn yuè", "full moon", "bulan purnama"],
    ["出来", "chū lái", "come out", "keluar"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["爬到", "pá dào", "climb onto", "memanjat ke"],
    ["其上", "qí shàng", "on it", "atasnya"],
    ["，", "", "", ""],
    ["翘望", "qiào wàng", "gazing", "memandang"],
    ["天边", "tiān biān", "horizon", "ufuk"],
    ["；", "", "", ""],
    ["奶奶", "nǎi nai", "Grandma", "Nenek"],
    ["总是", "zǒng shì", "always", "selalu"],
    ["要", "yào", "would", "akan"],
    ["骂", "mà", "scold", "memarahi"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["害怕", "hài pà", "afraid", "takut"],
    ["我们", "wǒ men", "we", "kami"],
    ["摔下来", "shuāi xià lái", "fall down", "jatuh"],
    ["。", "", "", ""],
    ["果然", "guǒ rán", "Indeed", "Sesungguhnya"],
    ["那一次", "nà yí cì", "that time", "pada masa itu"],
    ["就", "jiù", "then", "lalu"],
    ["摔了", "shuāi le", "fell", "jatuh"],
    ["下来", "xià lái", "", ""],
    ["，", "", "", ""],
    ["磕破", "kē pò", "scraped", "terluka"],
    ["了", "le", "", ""],
    ["我的", "wǒ de", "my", "saya punya"],
    ["膝盖", "xī gài", "knee", "lutut"],
    ["呢", "ne", "", ""],
    ["。", "", "", ""],
    ["人", "rén", "Everyone", "Semua orang"],
    ["都", "dōu", "all", "semua"],
    ["骂", "mà", "cursed", "memaki"],
    ["它", "tā", "it", "ia"],
    ["是", "shì", "as", "sebagai"],
    ["丑石", "chǒu shí", "ugly stone", "batu buruk"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["真是", "zhēn shì", "truly is", "benar-benar"],
    ["丑得", "chǒu de", "ugly to", "buruk sehingga"],
    ["不能再丑", "bù néng zài chǒu", "cannot be uglier", "tidak boleh lagi buruk"],
    ["的", "de", "", ""],
    ["丑石", "chǒu shí", "ugly stone", "batu buruk"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["终有", "zhōng yǒu", "Finally there was", "Akhirnya ada"],
    ["一日", "yí rì", "one day", "suatu hari"],
    ["，", "", "", ""],
    ["村子里", "cūn zi lǐ", "in the village", "di kampung"],
    ["来了", "lái le", "came", "datang"],
    ["一个", "yí gè", "a", "seorang"],
    ["天文学家", "tiān wén xué jiā", "astronomer", "ahli astronomi"],
    ["。", "", "", ""],
    ["他", "tā", "He", "Dia"],
    ["在", "zài", "at", "di"],
    ["我家", "wǒ jiā", "my house", "rumah saya"],
    ["门前", "mén qián", "in front", "di hadapan"],
    ["路过", "lù guò", "passing by", "melalui"],
    ["，", "", "", ""],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["发现", "fā xiàn", "discovered", "menemui"],
    ["了", "le", "", ""],
    ["这块", "zhè kuài", "this", "ketul ini"],
    ["石头", "shí tou", "stone", "batu"],
    ["，", "", "", ""],
    ["眼光", "yǎn guāng", "his gaze", "pandangannya"],
    ["立即", "lì jí", "immediately", "serta-merta"],
    ["就", "jiù", "then", "lalu"],
    ["拉直", "lā zhí", "fixed", "tertumpu"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["他", "tā", "He", "Dia"],
    ["再", "zài", "again", "lagi"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["走去", "zǒu qù", "leave", "pergi"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["住了下来", "zhù le xià lái", "stayed", "tinggal"],
    ["；", "", "", ""],
    ["以后", "yǐ hòu", "later", "kemudian"],
    ["又", "yòu", "again", "lagi"],
    ["来了", "lái le", "came", "datang"],
    ["好些人", "hǎo xiē rén", "many people", "ramai orang"],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["这是", "zhè shì", "this is", "ini adalah"],
    ["一块", "yí kuài", "a", "seketul"],
    ["陨石", "yǔn shí", "meteorite", "meteorit"],
    ["，", "", "", ""],
    ["从", "cóng", "from", "dari"],
    ["天上", "tiān shàng", "the sky", "langit"],
    ["落下来", "luò xià lái", "fell down", "jatuh"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["有", "yǒu", "has", "ada"],
    ["二三百年", "èr sān bǎi nián", "two or three hundred years", "dua tiga ratus tahun"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["是", "shì", "is", "ialah"],
    ["一件", "yí jiàn", "a", "satu"],
    ["了不起", "liǎo bù qǐ", "remarkable", "hebat"],
    ["的", "de", "", ""],
    ["东西", "dōng xi", "thing", "benda"],
    ["。", "", "", ""],
    ["不久", "bù jiǔ", "Soon", "Tidak lama"],
    ["便", "biàn", "then", "lalu"],
    ["来了", "lái le", "came", "datang"],
    ["车", "chē", "vehicle", "kenderaan"],
    ["，", "", "", ""],
    ["小心翼翼地", "xiǎo xīn yì yì de", "carefully", "dengan berhati-hati"],
    ["将它", "jiāng tā", "it", "ia"],
    ["运走", "yùn zǒu", "took away", "membawa pergi"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["这", "zhè", "This", "Ini"],
    ["使", "shǐ", "made", "membuatkan"],
    ["我们", "wǒ men", "us", "kami"],
    ["都", "dōu", "all", "semua"],
    ["很", "hěn", "very", "sangat"],
    ["惊奇", "jīng qí", "surprised", "terkejut"],
    ["！", "", "", ""],
    ["这", "zhè", "This", "Ini"],
    ["又怪", "yòu guài", "strange", "pelik"],
    ["又丑", "yòu chǒu", "and ugly", "dan buruk"],
    ["的", "de", "", ""],
    ["石头", "shí tou", "stone", "batu"],
    ["，", "", "", ""],
    ["原来", "yuán lái", "it turned out", "rupanya"],
    ["是", "shì", "was", "ialah"],
    ["天上的", "tiān shàng de", "from the sky", "dari langit"],
    ["呢", "ne", "", ""],
    ["！", "", "", ""],
    ["它", "tā", "It", "Ia"],
    ["补过", "bǔ guò", "once mended", "pernah menambal"],
    ["天", "tiān", "the sky", "langit"],
    ["，", "", "", ""],
    ["在", "zài", "in", "di"],
    ["天上", "tiān shàng", "the sky", "langit"],
    ["发过", "fā guò", "emitted", "mengeluarkan"],
    ["热", "rè", "heat", "haba"],
    ["，", "", "", ""],
    ["闪过", "shǎn guò", "shone", "bersinar"],
    ["光", "guāng", "light", "cahaya"],
    ["，", "", "", ""],
    ["我们的", "wǒ men de", "our", "kita punya"],
    ["先祖", "xiān zǔ", "ancestors", "nenek moyang"],
    ["或许", "huò xǔ", "perhaps", "mungkin"],
    ["仰望过", "yǎng wàng guò", "looked up at", "memandang"],
    ["它", "tā", "it", "ia"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["给了", "gěi le", "gave", "memberi"],
    ["他们", "tā men", "them", "mereka"],
    ["光明", "guāng míng", "light", "cahaya"],
    ["、", "", "", ""],
    ["向往", "xiàng wǎng", "aspiration", "cita-cita"],
    ["、", "", "", ""],
    ["憧憬", "chōng jǐng", "hope", "harapan"],
    ["；", "", "", ""],
    ["而", "ér", "and", "dan"],
    ["它", "tā", "it", "ia"],
    ["落下来", "luò xià lái", "fell", "jatuh"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["在", "zài", "in", "dalam"],
    ["污土", "wū tǔ", "dirt", "tanah kotor"],
    ["里", "lǐ", "", ""],
    ["，", "", "", ""],
    ["荒草", "huāng cǎo", "weeds", "rumput liar"],
    ["里", "lǐ", "", ""],
    ["，", "", "", ""],
    ["一躺", "yì tǎng", "lay", "terbaring"],
    ["就是", "jiù shì", "for", "selama"],
    ["几百年", "jǐ bǎi nián", "hundreds of years", "beratus-ratus tahun"],
    ["了", "le", "", ""],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["奶奶", "nǎi nai", "Grandma", "Nenek"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["真", "zhēn", "Really", "Sungguh"],
    ["看不出", "kàn bù chū", "can't tell", "tidak nampak"],
    ["！", "", "", ""],
    ["它", "tā", "It", "Ia"],
    ["那么", "nà me", "so", "begitu"],
    ["不一般", "bù yì bān", "extraordinary", "luar biasa"],
    ["，", "", "", ""],
    ["却", "què", "yet", "tetapi"],
    ["怎么", "zěn me", "how", "bagaimana"],
    ["连", "lián", "even", "pun"],
    ["墙", "qiáng", "wall", "dinding"],
    ["也", "yě", "also", "juga"],
    ["垒不成", "lěi bù chéng", "can't build", "tidak boleh bina"],
    ["，", "", "", ""],
    ["台阶", "tái jiē", "steps", "tangga"],
    ["也", "yě", "also", "juga"],
    ["垒不成", "lěi bù chéng", "can't build", "tidak boleh bina"],
    ["呢", "ne", "", ""],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["“", "", "", ""],
    ["它", "tā", "It", "Ia"],
    ["是", "shì", "is", "ialah"],
    ["太丑", "tài chǒu", "too ugly", "terlalu buruk"],
    ["了", "le", "", ""],
    ["。”", "", "", ""],
    ["天文学家", "tiān wén xué jiā", "The astronomer", "Ahli astronomi"],
    ["说", "shuō", "said", "berkata"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["“", "", "", ""],
    ["真的", "zhēn de", "Truly", "Benar"],
    ["，", "", "", ""],
    ["是", "shì", "is", "ialah"],
    ["太丑", "tài chǒu", "too ugly", "terlalu buruk"],
    ["了", "le", "", ""],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    ["“", "", "", ""],
    ["可", "kě", "But", "Tetapi"],
    ["这", "zhè", "this", "ini"],
    ["正是", "zhèng shì", "is precisely", "itulah"],
    ["它", "tā", "its", "ia punya"],
    ["的", "de", "", ""],
    ["美", "měi", "beauty", "kecantikan"],
    ["！”", "", "", ""],
    ["天文学家", "tiān wén xué jiā", "the astronomer", "ahli astronomi"],
    ["说", "shuō", "said", "berkata"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["它", "tā", "It", "Ia"],
    ["是", "shì", "is", "ialah"],
    ["以丑为美", "yǐ chǒu wéi měi", "finding beauty in ugliness", "menjadikan buruk sebagai cantik"],
    ["的", "de", "", ""],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    ["“", "", "", ""],
    ["以丑为美", "yǐ chǒu wéi měi", "Beauty in ugliness", "Buruk sebagai cantik"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    ["“", "", "", ""],
    ["是的", "shì de", "Yes", "Ya"],
    ["，", "", "", ""],
    ["丑到", "chǒu dào", "Ugly to", "Buruk sehingga"],
    ["极处", "jí chù", "extreme", "tahap melampau"],
    ["，", "", "", ""],
    ["便是", "biàn shì", "it becomes", "itulah"],
    ["美到", "měi dào", "beauty to", "cantik sehingga"],
    ["极处", "jí chù", "extreme", "tahap melampau"],
    ["。", "", "", ""],
    ["正因", "zhèng yīn", "Precisely because", "Sebab"],
    ["为", "wèi", "", ""],
    ["它", "tā", "it", "ia"],
    ["不是", "bú shì", "is not", "bukan"],
    ["一般", "yì bān", "ordinary", "biasa"],
    ["的", "de", "", ""],
    ["顽石", "wán shí", "stone", "batu"],
    ["，", "", "", ""],
    ["当然", "dāng rán", "certainly", "tentu"],
    ["不能", "bù néng", "cannot", "tidak boleh"],
    ["去", "qù", "be used", "digunakan"],
    ["做墙", "zuò qiáng", "for walls", "untuk dinding"],
    ["、", "", "", ""],
    ["做台阶", "zuò tái jiē", "for steps", "untuk tangga"],
    ["，", "", "", ""],
    ["不能", "bù néng", "cannot", "tidak boleh"],
    ["去", "qù", "be used", "digunakan"],
    ["雕刻", "diāo kè", "carve", "mengukir"],
    ["、", "", "", ""],
    ["捶布", "chuí bù", "beat cloth", "memukul kain"],
    ["。", "", "", ""],
    ["它", "tā", "It", "Ia"],
    ["不是", "bú shì", "is not", "bukan"],
    ["做", "zuò", "for", "untuk"],
    ["这些", "zhè xiē", "these", "ini"],
    ["小玩意儿的", "xiǎo wán yì r de", "small purposes", "benda kecil"],
    ["，", "", "", ""],
    ["所以", "suǒ yǐ", "so", "maka"],
    ["常常", "cháng cháng", "often", "selalu"],
    ["就", "jiù", "then", "lalu"],
    ["遭到", "zāo dào", "suffer", "mendapat"],
    ["一般", "yì bān", "common", "biasa"],
    ["世俗", "shì sú", "worldly", "masyarakat"],
    ["的", "de", "", ""],
    ["讥讽", "jī fěng", "ridicule", "ejekan"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    ["奶奶", "nǎi nai", "Grandma", "Nenek"],
    ["脸红了", "liǎn hóng le", "blushed", "muka merah"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["也", "yě", "also", "juga"],
    ["脸红了", "liǎn hóng le", "blushed", "muka merah"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["感到", "gǎn dào", "felt", "merasa"],
    ["自己的", "zì jǐ de", "my own", "diri sendiri punya"],
    ["可耻", "kě chǐ", "shame", "kemaluan"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["感到", "gǎn dào", "felt", "merasa"],
    ["了", "le", "", ""],
    ["丑石", "chǒu shí", "the ugly stone's", "batu buruk punya"],
    ["的", "de", "", ""],
    ["伟大", "wěi dà", "greatness", "kebesaran"],
    ["；", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["甚至", "shèn zhì", "even", "malah"],
    ["怨恨", "yuàn hèn", "resented", "membenci"],
    ["它", "tā", "it", "ia"],
    ["这么", "zhè me", "so", "begitu"],
    ["多年", "duō nián", "many years", "bertahun-tahun"],
    ["竟", "jìng", "could", "boleh"],
    ["会", "huì", "", ""],
    ["默默地", "mò mò de", "silently", "dengan senyap"],
    ["忍受", "rěn shòu", "endure", "menahan"],
    ["着", "zhe", "", ""],
    ["这一切", "zhè yī qiè", "all this", "semua ini"],
    ["？", "", "", ""],
    ["而", "ér", "and", "dan"],
    ["我", "wǒ", "I", "Saya"],
    ["又", "yòu", "again", "lagi"],
    ["立即", "lì jí", "immediately", "serta-merta"],
    ["深深地", "shēn shēn de", "deeply", "dengan mendalam"],
    ["感到", "gǎn dào", "felt", "merasa"],
    ["它", "tā", "its", "ia punya"],
    ["那种", "nà zhǒng", "that kind of", "jenis"],
    ["不屈", "bù qū", "unyielding", "tidak tunduk"],
    ["于", "yú", "to", "pada"],
    ["误解", "wù jiě", "misunderstanding", "salah faham"],
    ["、", "", "", ""],
    ["寂寞", "jì mò", "lonely", "sunyi"],
    ["的", "de", "", ""],
    ["生存", "shēng cún", "existence", "kehidupan"],
    ["的", "de", "", ""],
    ["伟大", "wěi dà", "greatness", "kebesaran"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["贾平凹", "jiǎ píng wā", "Jia Pingwa", "Jia Pingwa"],
    ["《", "", "", ""],
    ["丑石", "chǒu shí", "The Ugly Stone", "Batu Buruk"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
